# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: linux-latest

steps:
- task: FlutterInstall@0
  inputs:
    mode: 'auto'
    channel: 'stable'
    version: 'custom'
    customVersion: '2.5.1'

- task: CmdLine@2
  inputs:
    script: 'echo ''##vso[task.setvariable variable=path]$(PATH):/Users/runner/hostedtoolcache/Flutter/2.5.1-stable/macos/flutter/bin'''

- task: CmdLine@2
  inputs:
    script: 'flutter pub get'

- task: CmdLine@2
  inputs:
    script: 'flutter build apk'
